#!/usr/bin/awk -f

# A script that turns fasta files into tab-separated files

{
	if (substr($1,1,1)==">")
		if (NR>1)
			printf "\n%s\t", substr($0,2,length($0)-1)
		else
			printf "%s\t", substr($0,2,length($0)-1)
	else
		printf "%s", $0

}END{printf "\n"}
